services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: fitness_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ranaghat@1
    ports:
      - "5433:5432"

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27018:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"

  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "8888:8888"

  userservice:
    build: ./userservice
    container_name: userservice
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: Ranaghat@1
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy

  activityservice:
    build: ./activityservice
    container_name: activityservice
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy

  aiservice:
    build: ./aiservice
    container_name: aiservice
    environment:
      GEMINI_API_KEY: AIzaSyAgluFNwM9uWmqDEYFDsvA3EXKpiLjcYeA
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "9999:9999"
    depends_on:
      keycloak:
        condition: service_healthy
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy