spring:
  cloud:
    client:
      hostname: activityservice
  mongodb:
    uri: mongodb://mongo:27017/fitnessActivity
    database: fitnessActivity
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: false

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
