spring:
  mongodb:
    uri: mongodb://mongo:27017/fitnessRecommendations
    database: fitnessRecommendations
  cloud:
    client:
      hostname: aiservice
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: false

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    key: ${GEMINI_API_KEY}