spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/fitness-oauth2/protocol/openid-connect/certs

  cloud:
    client:
      hostname: gateway
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/users/**

            - id: activityservice
              uri: lb://ACTIVITYSERVICE
              predicates:
                - Path=/api/activities/**

            - id: aiservice
              uri: lb://AISERVICE
              predicates:
                - Path=/api/recommendations/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: false

