spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fitness_user_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    client:
      hostname: userservice

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: false