# config-server

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
    client:
      hostname: configserver

server:
  port: 8888